### PR TITLE
Fix code style

### PR DESCRIPTION
**Pull request by JohnTitor**
Run clippy and rustfmt

### CODE REVIEW

**Comment by stappersg** [comment]
LGTM

**Comment by killercup** [comment]
Please note that the original formatting was chosen so that the code looks good when included in the book! Is that still the case?

**Comment by stappersg** [comment]
Looks good to me, the long version:

Patch
* sorts `use` alfabethicly
* does proper ident  ( yes, that is a white space change )
* inserts a line break (yes,  another WSC)
* changes some `Box<Error>>` into `Box<dyn Error>>`
* has good short description: _Fix code style_
* has good long description: _Run clippy and rustfmt_

It is not important why this patch needed to wait seven weeks before it got it's first response.
Important is that someone says which parts of this patch are good for acceptence.

**Comment by killercup** [comment]
@stappersg, thank you for the reivew. Sadly, the main issue is that this code is also included in the rendered book, where a different style might be required. The reason why it takes long for people to review PRs is that this is a project run by volunteers who only have so many hours per day 🤷‍♂

**Comment by spacekookie** [comment]
> It is not important why this patch needed to wait seven weeks before it got it's first response.
> Important is that someone says which parts of this patch are good for acceptence.

Not sure it's exactly nice to shame people maintaining public resources for not responding fast enough.

Apart from that, I feel that sorting imports is probably a trivial change, but changing the formatting of code sections is not something that I'd want to have done on a global scale. The point of code examples isn't to be idiomatic, but to be easy teaching resources. As such, formatting might not be the most important aspect of it

**Comment by JohnTitor** [comment]
Hm, I have no strong opinion for this, just close then.

**Comment by stappersg** [comment]
> Hm, I have no strong opinion for this, just close then.

Thanks for taking action.

Please, pretty please, keep submitting merge requests.

**Pull request closed without merging**
